variables:
  GIT_STRATEGY: fetch
  DOCKER_FILE: utils/Dockerfile
  DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
  DOCKER_IMAGE_DEV: pycity_scheduling


stages:
  - prepare
  - test

prepare:
  stage: prepare
  script:
    - docker build
        --file ${DOCKER_FILE}
        --target base
        --tag ${DOCKER_IMAGE_DEV}:base-${DOCKER_TAG} .
    - docker build
        --file ${DOCKER_FILE}
        --target lint
        --tag ${DOCKER_IMAGE_DEV}:lint-${DOCKER_TAG} .
  tags:
    - shell
    - linux

unittest:
  stage: test
  image: ${DOCKER_IMAGE_DEV}:base-${DOCKER_TAG}
  tags:
    - docker
  script:
    - mkdir /opt/gurobi
    - mv $GUROBI_LIC /opt/gurobi/gurobi.lic
    - cd $CI_PROJECT_DIR
    - pip3 install .
    - cd testing/unit_tests
    - python3 -m unittest discover

lint:
  stage: test
  image: ${DOCKER_IMAGE_DEV}:lint-${DOCKER_TAG}
  tags:
    - docker
  script:
    - cd $CI_PROJECT_DIR
    - pip3 install .
    - pylint --rcfile=./utils/.pylintrc pycity_scheduling > report.txt || true
    - tail -n 3 report.txt
  artifacts:
    name: "Pylint Report"
    paths:
      - report.txt
    expire_in: 2 weeks
    when: always
